### ISSUE TITLE
Invalid handle

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-mapchooser_extended#10]
cc: https://github.com/srcdslab/sm-plugin-mapchooser_extended/commit/a7a06e0ded2a31a5f47c097cc817632d2a5d852c

L 01/26/2023 - 11:22:15: [SM] Exception reported: Handle c100d6d is invalid (error 1)
L 01/26/2023 - 11:22:15: [SM] Blaming: mapchooser_extended/nominations_extended.smx
L 01/26/2023 - 11:22:15: [SM] Call stack trace:
L 01/26/2023 - 11:22:15: [SM]   [0] CloseHandle
L 01/26/2023 - 11:22:15: [SM]   [1] Line 201, mapchooser_extended/addons/sourcemod/scripting/nominations_extended.sp::OnConfigsExecuted

L 01/26/2023 - 11:22:12: [SM] Exception reported: Handle c100d6d is invalid (error 3)
L 01/26/2023 - 11:22:12: [SM] Blaming: mapchooser_extended/nominations_extended.smx
L 01/26/2023 - 11:22:12: [SM] Call stack trace:
L 01/26/2023 - 11:22:12: [SM]   [0] CloseHandle
L 01/26/2023 - 11:22:12: [SM]   [1] Line 157, mapchooser_extended/addons/sourcemod/scripting/nominations_extended.sp::OnMapEnd

No point of deleting it. Should be null.
Automaticly free with TIMER_FLAG_NO_MAPCHANGE

**Comment by maximee-leroyy** [comment]
ah yeah i forget about that everytime thanks
- https://github.com/srcdslab/sm-plugin-mapchooser_extended/commit/a7970655b9f7e025c43874a61c39c4dc8a3e2dbc
