### ISSUE TITLE
Error when compiling rockthevote

### ISSUE THREAD

**Issue by umbr1X** [srcdslab/sm-plugin-mapchooser_extended#12]
error 417: cannot read from file: "AFKManager"
error 417: cannot read from file: "PlayerManager"

**Comment by Rushaway** [comment]
I will add change to put them as tryinclude instead. I will ping you when the changes are done.

**Comment by umbr1X** [comment]
but still it says it does not recognize some functions, why not upload the both of the inc files?

**Comment by Rushaway** [comment]
More logs will be appreciate. 

https://github.com/srcdslab/sm-plugin-AFKManager
https://github.com/srcdslab/sm-plugin-PlayerManager

**Comment by maximee-leroyy** [comment]
optional support has been added thanks to @Rushaway here:
- https://github.com/srcdslab/sm-plugin-mapchooser_extended/commit/c839bc6a4d69014f7305886043ab22d55fa6527c
