### ISSUE TITLE
feat: get history of commits from fork

### ISSUE THREAD

**Issue by maximee-leroyy** [srcdslab/sm-plugin-mapchooser_extended#26]
Fork it from here:
- https://github.com/powerlord/sourcemod-mapchooser-extended

Then add back our commits

**Comment by Rushaway** [comment]
Good idea

**Comment by maximee-leroyy** [comment]
done here:
- https://github.com/srcdslab/sm-plugin-mapchooser-extended/commit/1dc8ce945a84ff4fee34eabf1183a29dfe92911f
