### ISSUE TITLE
fix: confusing function names

### ISSUE THREAD

**Issue by maximee-leroyy** [srcdslab/sm-plugin-mapchooser_extended#34]
GetMapAdminRestriction -> IsClientMapAdminRestricted
GetMapVIPRestriction -> IsClientMapVIPRestricted
GetMapLeaderRestriction -> IsClientMapLeaderRestricted

**Comment by Rushaway** [comment]
Can be breaking changes, since it's used as native.

**Comment by maximee-leroyy** [comment]
where are they used?

**Comment by Rushaway** [comment]
> where are they used?

As native irc. Not home and can't really check.

**Comment by Rushaway** [comment]
https://github.com/srcdslab/sm-plugin-mapchooser_extended/blob/master/addons/sourcemod/scripting/include/mapchooser_extended.inc#L140-#L152

https://github.com/srcdslab/sm-plugin-mapchooser_extended/blob/master/addons/sourcemod/scripting/mapchooser_extended.sp#L448-#L455

**Comment by maximee-leroyy** [comment]
i meant in which plugin are these natives used

**Comment by Rushaway** [comment]
Only in MCE, based on all repos stored on srcdslab.

**Comment by maximee-leroyy** [comment]
ok then no problem to make the change

**Comment by Rushaway** [comment]
Can be closed.
