### ISSUE TITLE
error with rockthevote_extended.smx

### ISSUE THREAD

**Issue by osopolar-kun123** [srcdslab/sm-plugin-mapchooser_extended#38]
rockthevote_extended.smx (Rock The Vote Extended): Could not find required plugin "AFKManager"
What version of afkmanager is needed?
I am using this version but it keeps giving me an error :c
https://forums.alliedmods.net/showthread.php?p=708265

**Comment by Rushaway** [comment]
It's related to this version.
https://github.com/srcdslab/sm-plugin-AFKManager

**Comment by maximee-leroyy** [comment]
should be fixed in
- https://github.com/srcdslab/sm-plugin-mapchooser_extended/commit/d3e31688595d0a4b84b209407d26a71da9f24ab8
